### ISSUE TITLE
collections do not display in live preview

### ISSUE THREAD

**Issue by edmeehan** [CloudCannon/bookshop#140]
The documentation mentions you can [access collections out of the box](https://github.com/CloudCannon/bookshop/blob/main/guides/eleventy.adoc#live-editing-site-data-and-collections), but the live preview shows nothing. Also, if I apply a filter like "reverse" it errors and does not render any Bookshop components in the preview.  I know that filters are limited, but am I missing a step to see collections in live previews? The documentation mentions you should be able to access as normal 'collections.*' which works fine in a normal 11ty render, just not live preview. 

Running all the latest packages:
"@11ty/eleventy": "^2.0.0",
"@bookshop/browser": "^3.4.0",
"@bookshop/eleventy-bookshop": "^3.4.0",
"@bookshop/eleventy-engine": "^3.4.0",
"@bookshop/generate": "^3.4.0",
"@bookshop/sass": "^3.4.0",

On Node: 18.13.0

**Comment by edmeehan** [comment]
This appears to be a documentation issue. It reads "out of the box" yet you still need to apply it to the collections to the data_config. This is confusing as I would assume out of the box does not require me to make any additional configurations.

**Comment by bglw** [comment]
Hmm @edmeehan can you share what you had to add to `data_config` to get this to work? Collections should indeed work out of the box without touching `data_config`, but maybe something else is going on here.

For some insight — [this is the integration test](https://github.com/CloudCannon/bookshop/blob/95a83c7bbd3f4caafb60297dd51ff4d20f653783/javascript-modules/integration-tests/features/eleventy/live_editing/eleventy_bookshop_live_data.feature#L100-L133) for live editing an Eleventy collection. That test has no CloudCannon configuration file at all.

**Comment by edmeehan** [comment]
Yeah, something is happening with my setup, I can access a collection, but no data objects are being returned. So I can see the count of items but can't access the data. I am waist-deep on a project I need to deliver in 24 hours. So when I am done, I will revisit this and post my config. This is my first CloudCannon project and have had a lot of trail and error getting the config correct.

**Comment by edmeehan** [comment]
I am setting the tags using in a directory using an eleventy.js file - https://www.11ty.dev/docs/data-template-dir/

**Comment by edmeehan** [comment]
I tested adding the tags property directly in a few files in a collection and it still didn't work. When I output the collections items into a template I see [FILTERED] instead of [OBJECT] as expected.

<img width="676" alt="Screen Shot 2023-03-29 at 3 40 12 PM" src="https://user-images.githubusercontent.com/412189/228684132-d7d2dde4-55c7-4f68-845f-556b23d3dfdc.png">

**Comment by bglw** [comment]
Hmm.

Overall, this is definitely a case where I need to improve the documentation (which I am currently doing!)

Firstly just to check — if by live preview you're referring to the Bookshop component browser, collections will *not* work there. In the CMS Visual Editor though, these should be accessible.

Regarding the Visual Editor:
When Bookshop considers "collections" it isn't looking directly at any 11ty concept, but is instead using CloudCannon's understanding of collections. So the collections that are visible in your sidebar (or configured with [collections_config](https://cloudcannon.com/documentation/articles/defining-your-collections/)) are what will be available in the live preview.

Are the collections you're trying to access shown by CloudCannon in the CMS? 

_(Also, if you have any code base on hand that you can share I'd be happy to spin it up and dig in, which might be the quickest resolution)_

**Comment by edmeehan** [comment]
Yeah, this is in CC visual editor live preview. The only thing I am finding that could be the issue, is when my site builds I notice some added messages regarding collections.

The collection I am working with is "events" - but in the screen shot you can see it is empty and it processes all the subfolders with collections names like "events/2020" with X files.

I wonder if this has something to do with CC collection vs 11ty collection.

<img width="567" alt="Screen Shot 2023-03-29 at 4 05 20 PM" src="https://user-images.githubusercontent.com/412189/228687739-4031aea1-6709-4971-8cf6-94d6dd868e5d.png">

**Comment by edmeehan** [comment]
Yes, I can confirm now that my issue is related to how CC interprets collections (based on the log) differs from what 11ty defines as collections.

As a test, I tried the "pages" collection and was able to access the data.
I was not able to access the "events" collection (but 11ty can access it), but I could access the "events/2017" collection.

**Comment by edmeehan** [comment]
To summarize the issue, this appears that collections are not the same between CC and 11ty.

It appears CC collections are based on folders in the app, while 11ty is defined by the tags property in the front matter.

This can be seen in the build log above.

**Comment by edmeehan** [comment]
I read thru the CC documentation related to collections. I only see mention of folders defining collections. In my case, I have a collections folder but also subfolders, and I want all files on those subfolders to be a part of the parent collection and not a new subfolder collection.

I do define collections in my config as such:
`collections_config: {
    events: {
      path: 'events'
    }
}`

**Comment by edmeehan** [comment]
Going to close this again since you can work around it with configs... but should allow collections to reflect the SSG like eleventy.

Just incase someone hits this same wall. I solved this by using the dynamic permalink option in front matter for 11ty.

screen shot of my CC collections now that all files are in a single folder:
<img width="578" alt="Screen Shot 2023-03-29 at 8 03 44 PM" src="https://user-images.githubusercontent.com/412189/228717975-58627675-6bf6-4f86-b696-2d6cd6defc5f.png">

**Comment by bglw** [comment]
Yes, CloudCannon collections correspond strictly to folders rather than SSG concepts like tags — since the core CMS is generic over SSGs it's the best path there, so that is unlikely to change.

I'll keep this in mind though for whether Bookshop could support remapping content to match an 11ty collection — it depends on what data we have ans when. I'll jump back into this thread if I make any progress on that in the future. In the meantime I'm writing new Bookshop 11ty documentation, so I'll make the semantics of this super clear.
