### ISSUE TITLE
using Astro.slots.render() breaks live editing

### ISSUE THREAD

**Issue by silveltman** [CloudCannon/bookshop#178]
using Astro.slots.render() breaks live editing:
```astro
---
const slot = await Astro.slots.render('default')
---

{
  slot?.length > 4 && (
    <section>
      <slot />
    </section>
  )
}
```

using Astro.slots.has() also breaks live editing

**Comment by Tate-CC** [comment]
Hi @silveltman!

This issue should be fixed in yesterdays release of Bookshop 3.9.0!
