### ISSUE TITLE
Hugo bookshop_bindings not found

### ISSUE THREAD

**Issue by isaac1620** [CloudCannon/bookshop#194]
Error:

themes/cook/layouts/product-tour/single.html:2:7": execute of template failed: template: product-tour/single.html:2:7: executing "main" at <partial "bookshop_bindings" `.Params`>: error calling partial: partial "bookshop_bindings" not found

themes/cook/layouts/product-tour/single.html:1:3": execute of template failed: template: product-tour/single.html:1:3: executing "product-tour/single.html" at <partial "bookshop" (slice "sample" (dict "text" "Hello from the sample component"))>: error calling partial: partial "bookshop" not found

**Comment by bglw** [comment]
👋 Hi @isaac1620 

The first thing to check would be that the Hugo module is correctly added — making sure `require github.com/cloudcannon/bookshop/hugo/v3` is in your `go.mod` file and that the equivalent import is in your `config.toml`.

If those are correct, it's usually the case that Hugo itself is confused about its current modules. When that happens, I find that running `hugo mod clean` followed by `hugo mod tidy` can set things right.

Let me know if that resolves things for you :)

**Comment by bglw** [comment]
Thanks for the code samples @isaac1620 :) 

Can you try removing the `themes/cook/` prefix from the `target` values in your component library config?

In other words, try:

// component-library/config.toml

```toml
[[module.mounts]]
source = "."
target = "layouts/partials/bookshop"

[[module.mounts]]
source = "."
target = "assets/bookshop"
```

The `target` here isn't looking for a path on your filesystem, but instead a path that Hugo should pretend the file is at in its internal "virtual filesystem".
Per the [Hugo docs](https://gohugo.io/hugo-modules/configuration/#default-mounts): 

> Where it should be mounted into Hugo’s virtual filesystem. It must start with one of Hugo’s component folders: `static`, `content`, `layouts`, `data`, `assets`, `i18n`, or `archetypes`.

**Comment by bglw** [comment]
Ah, glad to hear it's working :) I'll make an edit to the docs to make that clearer.

**Comment by bglw** [comment]
Hey again @isaac1620 👋 

It is possible, but it requires a bit more setup work to get these files in place, as Bookshop in the Visual Editor uses its own Hugo setup that doesn't share your files on disk (hence the error).

The process for this is documented here: https://github.com/CloudCannon/bookshop/blob/main/guides/hugo-extra-files.md

As an example, I would expect something like the following Bookshop config to help in your situation:

```js
const fs = require("fs");

module.exports = {
  engines: {
    "@bookshop/hugo-engine": {
      extraFiles: {
        "layouts/partials/hero-heading.html": fs.readFileSync("themes/cook/layouts/partials/hero-heading.html", { encoding: "utf8" })
      }
    }
  }
}
```

_(I would avoid mapping files to a theme directory for Bookshop, as the Hugo site it simulates doesn't use a theme. In the above example, I'm just placing the component from the repo's themes directory into the simulated Hugo's main partials directory)_

Let me know if that gets you going :)
