### ISSUE TITLE
[FEATURE] Upgrade embedded Hugo renderer for live editing

### ISSUE THREAD

**Issue by markdumay** [CloudCannon/bookshop#200]
The current Hugo renderer is pinned to version v0.111.3:

https://github.com/CloudCannon/bookshop/blob/de6f5202b074d62257c81777ae42409c589cbe90/javascript-modules/engines/hugo-engine/full-hugo-renderer/go.mod#L8

This Hugo version was released in March 2013. Since then, major new features have been added to Hugo. It would be great if the embedded Hugo renderer could be upgraded to a more recent version.

Ideally, the compiled Hugo wasm would use the exact same version as defined in the [build pipeline](https://cloudcannon.com/documentation/articles/configuring-your-build/#setting-your-ssg-version). This would greatly reduce unexpected build errors during live editing, as these errors do not show up during the site build otherwise. Alternatively, you could include a warning in the bookshop docs about the supported Hugo version for live editing.

**Comment by bglw** [comment]
Shipped in [v3.11.0](https://github.com/CloudCannon/bookshop/releases/tag/v3.11.0) 🙂 

_(Unfortunately this is hard to do automatically since Bookshop hooks into internal unstable endpoints that change a lot)_
