### ISSUE TITLE
CloudCannon Bookshop Svelte ?

### ISSUE THREAD

**Issue by jbruxelle** [CloudCannon/bookshop#65]
Hi ! 

What is the state of art concerning Svelte Bookshop integration in CloudCannon ? 

I actually found the bookshop/svelte-engine but I guess I need an additional layer to set it up in CloudCannon.
Is it under development / planned / whatever ?

However, I'd like to say you guys are doing great jobs here ! 🔥 

Thanks in advance.

**Comment by matindow** [comment]
I hate to just write an "is there any update?" comment without anything to add, but I am eager to use cloudcannon/bookshop with a sveltekit site so am curious what the current state/timeline is? Thanks!

**Comment by bglw** [comment]
Hi all!

Sorry for the delay on this work — a few weeks from October has certainly taken some time. 

Shipping Svelte support is firmly in my plans for this month, pending any unforeseen difficulties. I'll set a reminder to update this issue with my progress in a couple of weeks.

**Comment by bglw** [comment]
Hello! Long overdue, but SvelteKit support has finally shipped in v3.3.0 😄
