### ISSUE TITLE
Possible docs typo

### ISSUE THREAD

**Issue by mneumegen** [CloudCannon/bookshop#92]
In the [Hugo Bookshop guide](https://github.com/CloudCannon/bookshop/blob/main/guides/hugo.adoc), it instructs to put the mount configuration at `components/config.toml`. I thought this meant `/component-library/components/config.toml`. After looking at example sites, I've found it should be `/component-library/config.toml`.

**Comment by bglw** [comment]
I think this is addressed well in the new documentation 

_(also, the init command will now create this file for you 😄)_
